INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Oxford', 'O1', '1K');
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Oxford', 'O2', '1Q');
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Cambridge', 'C1', '1K');
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Cambridge', 'C2', '1K');
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Victoria', 'V1', '1K');
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Victoria', 'V2', '1Q');
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Victoria', 'V3', '2D');
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Manchester', 'M1', '1K');
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Manchester', 'M2', '1K');

INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES('Adams', 'Martin', 'madams2b@msu.edu', 'China', '4 Mandrake Plaza', '', '9-(401)660-9813');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES('Johnson', 'Kevin', 'kjohnson2h@unesco.org', 'Poland', '5 Haas Circle', '', '8-(553)359-6387');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES('Rose', 'Sarah', 'srose1@japanpost.jp', 'United States', '3147 3rd Place', 'CA', '9-(625)374-4080');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES('Young', 'Judith', 'jyoung11@goodreads.com', 'United States', '2 Sachtjen Parkway', 'WV', '9-(659)879-6466');

-- Guest Young Judith books Cambridge Room C2 on 1st Jan 2019
INSERT INTO RESERVATION (ROOM_ID, GUEST_ID, RES_DATE) VALUES ((SELECT ROOM_ID FROM ROOM WHERE ROOM_NUMBER = 'C2'), (SELECT GUEST_ID FROM GUEST WHERE LAST_NAME = 'Young'), '2019-01-01');

